blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/Acik-Kaynak-Gelistirme-Toplulugu/ro-Control/discussions
    about: Ask questions or share ideas in Discussions
